-- DecideCasa Borrador (Supabase/Postgres)
-- Run in Supabase SQL editor.

-- Extensions
create extension if not exists pgcrypto;

-- Leads captured from landing and/or buyer brief
create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  source text not null default 'landing',
  status text not null default 'new',

  company text,
  role text,
  name text not null,
  phone text not null,
  email text not null,

  district text,
  budget_usd numeric,
  bedrooms text,
  timeline text,
  notes text,

  utm jsonb
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_email_idx on public.leads (email);

-- Snapshot de recomendaciones generadas por lead
create table if not exists public.lead_recommendations (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads(id) on delete cascade,
  generated_at timestamptz not null default now(),
  top_project_code text,
  top_score numeric,
  recommendations jsonb not null
);

create index if not exists lead_reco_lead_id_idx on public.lead_recommendations (lead_id);

-- Eventos de producto (server-side)
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  ts_utc timestamptz not null,
  name text not null,
  props jsonb
);

create index if not exists events_ts_idx on public.events (ts_utc desc);
create index if not exists events_name_idx on public.events (name);

-- RLS (opcional). Para borrador, puedes deshabilitar RLS en estas tablas.
-- alter table public.leads enable row level security;
-- alter table public.lead_recommendations enable row level security;
-- alter table public.events enable row level security;
